#!/bin/bash

# TO DO MANUALLY: Ensure DNS servers are correct in /etc/resolv.conf, ensure swap is setup

if [ "$#" -ne 2 ]; then
    echo "Usage: migrate <origin> <destination>"
    exit
fi

cd `dirname $0`
orig=$1
dest=$2

tmp=`mktemp -d 2>/dev/null || mktemp -d -t 'tmp'`

echo "Copying migration scripts to origin"
rsync -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -a --delete . root@"$orig":/opt/tkeith-migrator

echo "Copying migration scripts to destination"
rsync -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -a --delete . root@"$dest":/opt/tkeith-migrator

echo "Stopping services on origin"
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@"$orig" /opt/tkeith-migrator/stop-services

echo "Stopping services on destination"
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@"$dest" /opt/tkeith-migrator/stop-services

echo "Generating SSH key"
ssh-keygen -f "$tmp"/id_rsa -t rsa -N ''

echo "Copying SSH key"
rsync -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -a "$tmp"/id_rsa root@"$orig":/opt/tkeith-migrator/
rsync -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -a "$tmp"/id_rsa.pub root@"$dest":/opt/tkeith-migrator/
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@"$dest" "mkdir /root/.ssh; cat /opt/tkeith-migrator/id_rsa.pub >> /root/.ssh/authorized_keys"

echo "Migrating files"
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@"$orig" /opt/tkeith-migrator/do-migrate-files "$dest"
